=== pirulaire/DAW/Jordi Soto/act9.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>

<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
	<xs:element name="cadastre">
	<xs:complexType>
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="habitatge" type="habit" />
		</xs:choice>
	</xs:complexType>
	</xs:element>	   
	
	<xs:complexType name="habit">
	<xs:all>
		<xs:element name="localitzacio">
		<xs:complexType>
			<xs:all>
				<xs:element name="carrer" type="xs:string" />
				<xs:element name="numero" type="xs:string" />
				<xs:element name="planta_porta" type="xs:string" />
			</xs:all>
		</xs:complexType>
		</xs:element>
		<xs:element name="habitants" type="habitant" />
	</xs:all>
	<xs:attribute name="ref" type="xs:integer" />
	</xs:complexType>
	
	<xs:complexType name="habitant">
	<xs:choice minOccurs="1" maxOccurs="unbounded">
		<xs:element name="persona">
		<xs:complexType>
		<xs:all>
			<xs:element name="nif" type="xs:string" />
			<xs:element name="nom_cognoms" type="xs:string" />
			<xs:element name="data_naixement" type="xs:date" />
			<xs:element name="sexe" type="xs:string" />
		</xs:all>
		</xs:complexType>
		</xs:element>
	</xs:choice>
	</xs:complexType>
</xs:schema>

=== pirulaire/DAW/Jordi Soto/act9.xml
<?xml version="1.0" encoding="ISO-8859-15" ?>

<cadastre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="act9.xsd">
	<habitatge ref="142587">
		<localitzacio>
			<carrer>Del morro</carrer>
			<numero>24</numero>
			<planta_porta>2 3</planta_porta>
		</localitzacio>
		<habitants>
			<persona>
				<nif>52147852H</nif>
				<nom_cognoms>Trinitat Tarangon</nom_cognoms>
				<data_naixement>2000-01-20</data_naixement>
				<sexe>Dona</sexe>
			</persona>
			<persona>
				<nif>53268457J</nif>
				<nom_cognoms>Carles Carbonell</nom_cognoms>
				<data_naixement>1990-11-03</data_naixement>
				<sexe>Home</sexe>
			</persona>			
		</habitants>
	</habitatge>

</cadastre>
